/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CategoryList.java
 *
 * Created on Aug 16, 2012, 3:57:25 PM
 */
package com.wings4.client;

import com.towel.el.annotation.AnnotationResolver;
import com.towel.swing.table.ObjectTableModel;
import com.wings4.model.*;
import com.wings4.util.InventoryConstants;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ronnie
 */
public class CategoryList extends javax.swing.JFrame {

    /** Creates new form CategoryList */
    public CategoryList() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        categoryScrollPane = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();

        AnnotationResolver resolver = new AnnotationResolver(com.wings4.model.Category.class);
        final ObjectTableModel<com.wings4.model.Category> tableModel = new ObjectTableModel<com.wings4.model.Category>(
                resolver, "categoryId,categoryName,parentCategory");

        tableModel.setData(getData());
        categoryTable.setModel(tableModel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(InventoryConstants.resourceDirectory.
                concat("list-add.png"))));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        categoryScrollPane.setViewportView(categoryTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
            .addComponent(categoryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CategoryList().setVisible(true);
            }
        });
    }

    private List<com.wings4.model.Category> getData() {
        List<com.wings4.model.Category> list = new ArrayList<com.wings4.model.Category>();
        return list;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane categoryScrollPane;
    private javax.swing.JTable categoryTable;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
