/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wings4.client;

import com.wings4.Login;
import com.wings4.dao.DeliveryTermDao;
import com.wings4.dao.PaymentDao;
import com.wings4.dao.UserDao;
import com.wings4.util.*;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import javax.swing.*;

/**
 *
 * @author shohag
 */
public class SalesOrderCreate extends InventoryInternalBase {

    /**
     * Creates new form SalesOrderCreate
     */
    public SalesOrderCreate() {
        initComponents();
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jobNameLabel = new javax.swing.JLabel();
        jobNameTxt = new javax.swing.JTextField();
        orderQuantityLabel = new javax.swing.JLabel();
        orderQuantityTxt = new javax.swing.JTextField();
        createdDateLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        statusCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        priorityCombo = new javax.swing.JComboBox();
        sentLabel = new javax.swing.JLabel();
        sentCheck = new javax.swing.JCheckBox();
        dueDateLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        archaivedCheck = new javax.swing.JCheckBox();
        submitGeneralBtn = new javax.swing.JButton();
        cancelGeneral = new javax.swing.JButton();
        createdByLabel = new javax.swing.JLabel();


        createdDateTxt = new com.toedter.calendar.JDateChooser();
        dueDateTxt = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        paymentTermLabel = new javax.swing.JLabel();


        jLabel5 = new javax.swing.JLabel();


        jLabel6 = new javax.swing.JLabel();
        dueDateTermsCondition = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        organizationLbl = new javax.swing.JLabel();
        organizationTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        customerCombo = new javax.swing.JComboBox();
        submitDetailBtn = new javax.swing.JButton();
        cancelDetailBtn = new javax.swing.JButton();

        createdByCombo = new javax.swing.JComboBox(creatorItem());
        createdByCombo.setRenderer(new ItemRenderer());

        paymentTermCombo = new javax.swing.JComboBox(paymentTermItem());
        paymentTermCombo.setRenderer(new ItemRenderer());


        deliveryTermCombo = new javax.swing.JComboBox(deliveryTermItem());
        deliveryTermCombo.setRenderer(new ItemRenderer());

        jobNameLabel.setText("Job Name");

        orderQuantityLabel.setText("Order Quantity");

        createdDateLabel.setText("Created Date");

        statusLabel.setText("Status");

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Priority");

        priorityCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        sentLabel.setText("Sent");

        dueDateLabel.setText("Due Date");

        jLabel2.setText("Archived");

        submitGeneralBtn.setText("Submit");
        submitGeneralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitGeneralBtnActionPerformed(evt);
            }
        });

        cancelGeneral.setText("Cancel");

        createdByLabel.setText("Created By");



        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createdByLabel)
                    .addComponent(jLabel2)
                    .addComponent(dueDateLabel)
                    .addComponent(sentLabel)
                    .addComponent(jLabel1)
                    .addComponent(statusLabel)
                    .addComponent(createdDateLabel)
                    .addComponent(orderQuantityLabel)
                    .addComponent(jobNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(submitGeneralBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cancelGeneral))
                        .addComponent(jobNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addComponent(orderQuantityTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(priorityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sentCheck)
                        .addComponent(archaivedCheck))
                    .addComponent(createdByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createdDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jobNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderQuantityLabel)
                    .addComponent(orderQuantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createdDateLabel)
                    .addComponent(createdDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createdByLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel)
                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priorityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sentLabel)
                    .addComponent(sentCheck))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dueDateLabel)
                    .addComponent(dueDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(archaivedCheck))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitGeneralBtn)
                    .addComponent(cancelGeneral))
                .addContainerGap())
        );

        jTabbedPane1.addTab("General Information", jPanel1);

        paymentTermLabel.setText("Payment Term");



        jLabel5.setText("Delivery Term");



        jLabel6.setText("Due Date");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(paymentTermLabel))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(deliveryTermCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE)
                        .addComponent(paymentTermCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(dueDateTermsCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentTermLabel)
                    .addComponent(paymentTermCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(deliveryTermCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(dueDateTermsCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Terms and Conditions", jPanel3);

        jLabel3.setText("Customer ");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        organizationLbl.setText("Organization");

        jLabel4.setText("Address");

        customerCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        submitDetailBtn.setText("Submit");

        cancelDetailBtn.setText("Cancel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(organizationLbl)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(submitDetailBtn)
                        .addGap(18, 18, 18)
                        .addComponent(cancelDetailBtn))
                    .addComponent(organizationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationLbl)
                    .addComponent(organizationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitDetailBtn)
                    .addComponent(cancelDetailBtn))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Detail", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Vector<Item> creatorItem(){
        try{
//            System.out.println("userDao.findAllUsers() = " + userDao.findAllUsers());
            JSONArray jsonArray = new JSONArray(UserDao.findAllUsers());
            List<Map<String,Object>> users = new ArrayList<Map<String,Object>>();
            Map<String,Object> user;
            System.out.print(jsonArray.length());
            for(int i = 0 ; i < jsonArray.length(); i++){
                user = new HashMap<String,Object>();
                System.out.println("jsonArray.get(i) = " + jsonArray.get(i));
                JSONObject userObject = (JSONObject)jsonArray.get(i);
                user.put("id", userObject.get("id"));
                user.put("userCode", userObject.get("userCode"));
                users.add(user);
            }

            Vector<Item> userVector = new Vector<Item>();
            for(Map<String,Object> userMap : users) {
                System.out.println("userMap = " + userMap);
                userVector.addElement(new Item(Integer.parseInt(userMap.get("id").toString()), userMap.get("userCode").toString()));
            }
            return userVector;
        }catch(Exception ex){
            System.out.println("ex is here = " + ex);
            return null;
        }
    }


    private Vector<Item> paymentTermItem(){
        try{
            JSONArray jsonArray = new JSONArray(PaymentDao.findAllPayments());
            List<Map<String,Object>> payments = new ArrayList<Map<String,Object>>();
            Map<String,Object> payment;
            System.out.print(jsonArray.length());
            for(int i = 0 ; i < jsonArray.length(); i++){
                payment = new HashMap<String,Object>();
                System.out.println("jsonArray.get(i) = " + jsonArray.get(i));
                JSONObject paymentObject = (JSONObject)jsonArray.get(i);
                payment.put("id", paymentObject.get("id"));
                payment.put("paymentMethod", paymentObject.get("paymentMethod"));
                payments.add(payment);
            }

            Vector<Item> paymentVector = new Vector<Item>();
            for(Map<String,Object> paymentMap : payments) {
                System.out.println("paymentMap = " + paymentMap);
                paymentVector.addElement(new Item(Integer.parseInt(paymentMap.get("id").toString()), paymentMap.get("paymentMethod").toString()));
            }
            return paymentVector;
        }catch(Exception ex){
            System.out.println("ex is here = " + ex);
            return null;
        }
    }

    private Vector<Item> deliveryTermItem(){
        try{
            List<Map<String,Object>> deliveryTerms = new ArrayList<Map<String,Object>>();
            JSONArray jsonArray = new JSONArray(DeliveryTermDao.findAllDeliveryTerm());
            Map<String,Object> deliveryTerm;
            for(int i = 0 ; i < jsonArray.length(); i++){
                deliveryTerm = new HashMap<String,Object>();
                System.out.println("jsonArray.get(i) = " + jsonArray.get(i));
                JSONObject deliveryTermObject = (JSONObject)jsonArray.get(i);
                deliveryTerm.put("id", deliveryTermObject.get("id"));
                deliveryTerm.put("terms", deliveryTermObject.get("terms"));
                deliveryTerms.add(deliveryTerm);
            }

            Vector<Item> deliveryTermVector = new Vector<Item>();
            for(Map<String,Object> deliveryTermMap : deliveryTerms) {
                System.out.println("deliveryTermMap = " + deliveryTermMap);
                deliveryTermVector.addElement(new Item(Integer.parseInt(deliveryTermMap.get("id").toString()),
                        deliveryTermMap.get("terms").toString()));
            }
            return deliveryTermVector;
        }catch(Exception ex){
            System.out.println("ex is here = " + ex);
            return null;
        }
    }

    private void submitGeneralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitGeneralBtnActionPerformed
        JOptionPane.showConfirmDialog(this, "Submitted");
        JSONObject salesOrderObject = new JSONObject();
        try {
            Item createdBy = (Item)createdByCombo.getSelectedItem();
            salesOrderObject.put("jobName", jobNameTxt.getText());
            salesOrderObject.put("orderQuantity", orderQuantityTxt.getText());
            salesOrderObject.put("createdDate", createdDateTxt.getDate().toString());
            salesOrderObject.put("createdBy", createdBy.getId());
            salesOrderObject.put("status", statusCombo.getSelectedItem().toString());
            salesOrderObject.put("priority", priorityCombo.getSelectedItem().toString());
            salesOrderObject.put("isSent", sentCheck.isSelected());
            salesOrderObject.put("dueDate", dueDateTxt.getDate().toString());
            salesOrderObject.put("isArchived", archaivedCheck.isSelected());
            
        } catch (JSONException ex) {
            Logger.getLogger(SalesOrderCreate.class.getName()).log(Level.SEVERE, null, ex);
        }

        String restEndPoint = Login.getRestEndPoint();
        String resource = "salesOrder";



        RESTFeed restFeed = new RESTFeed(InventoryConstants.MEDIA_JSON,
                InventoryConstants.MEDIA_JSON,InventoryConstants.POST,
                restEndPoint, resource);
        restFeed.setJsonObject(salesOrderObject);
        try {
            restFeed.restInitialization();
        } catch (MalformedURLException ex) {
            Logger.getLogger(SalesOrderCreate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SalesOrderCreate.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_submitGeneralBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesOrderCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesOrderCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesOrderCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesOrderCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SalesOrderCreate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JCheckBox archaivedCheck;
    private javax.swing.JButton cancelDetailBtn;
    private javax.swing.JButton cancelGeneral;
    private javax.swing.JComboBox createdByCombo;
    private javax.swing.JLabel createdByLabel;
    private javax.swing.JLabel createdDateLabel;
    private com.toedter.calendar.JDateChooser createdDateTxt;
    private javax.swing.JComboBox customerCombo;
    private javax.swing.JComboBox deliveryTermCombo;
    private javax.swing.JLabel dueDateLabel;
    private com.toedter.calendar.JDateChooser dueDateTermsCondition;
    private com.toedter.calendar.JDateChooser dueDateTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jobNameLabel;
    private javax.swing.JTextField jobNameTxt;
    private javax.swing.JLabel orderQuantityLabel;
    private javax.swing.JTextField orderQuantityTxt;
    private javax.swing.JLabel organizationLbl;
    private javax.swing.JTextField organizationTxt;
    private javax.swing.JComboBox paymentTermCombo;
    private javax.swing.JLabel paymentTermLabel;
    private javax.swing.JComboBox priorityCombo;
    private javax.swing.JCheckBox sentCheck;
    private javax.swing.JLabel sentLabel;
    private javax.swing.JComboBox statusCombo;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton submitDetailBtn;
    private javax.swing.JButton submitGeneralBtn;
    // End of variables declaration//GEN-END:variables
}
