/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wings4.core;

import com.wings4.Login;


import com.wings4.util.*;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.json.JSONException;
import org.json.JSONObject;

import javax.swing.*;

/**
 *
 * @author shohag
 */
public class SalesOrderCreate extends InventoryInternalBase {

    /**
     * Creates new form SalesOrderCreate
     */
    public SalesOrderCreate() {
        initComponents();
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new JTabbedPane();
        jPanel1 = new JPanel();
        jobNameLabel = new JLabel();
        jobNameTxt = new JTextField();
        orderQuantityLabel = new JLabel();
        orderQuantityTxt = new JTextField();
        createdDateLabel = new JLabel();
        statusLabel = new JLabel();
        statusCombo = new JComboBox();
        jLabel1 = new JLabel();
        priorityCombo = new JComboBox();
        sentLabel = new JLabel();
        sentCheck = new JCheckBox();
        dueDateLabel = new JLabel();
        jLabel2 = new JLabel();
        archaivedCheck = new JCheckBox();
        submitGeneralBtn = new JButton();
        clearGeneral = new JButton();
        createdByLabel = new JLabel();


        createdDateTxt = new com.toedter.calendar.JDateChooser();
        dueDateTxt = new com.toedter.calendar.JDateChooser();
        jPanel3 = new JPanel();
        paymentTermLabel = new JLabel();


        jLabel5 = new JLabel();


        jLabel6 = new JLabel();
        dueDateTermsCondition = new com.toedter.calendar.JDateChooser();
        jPanel2 = new JPanel();
        jLabel3 = new JLabel();
        organizationLbl = new JLabel();
        organizationTxt = new JTextField();
        jLabel4 = new JLabel();
        addressTxt = new JTextField();
        customerCombo = new JComboBox();
        submitDetailBtn = new JButton();
        cancelDetailBtn = new JButton();

        createdByCombo = new JComboBox(ItemCreationCombo.comboInitialization("CommonDao","findAllUsers", "userCode"));
        createdByCombo.setRenderer(new ItemRenderer());

        paymentTermCombo = new JComboBox(ItemCreationCombo.comboInitialization("CommonDao","findAllPaymentTerms", "name"));
        paymentTermCombo.setRenderer(new ItemRenderer());


        deliveryTermCombo = new JComboBox(ItemCreationCombo.comboInitialization("CommonDao","findAllDeliveryTerms", "terms"));
        deliveryTermCombo.setRenderer(new ItemRenderer());

        setTitle("Sales Order Creation");

        jobNameLabel.setText("Job Name");

        orderQuantityLabel.setText("Order Quantity");

        createdDateLabel.setText("Created Date");

        statusLabel.setText("Status");

        statusCombo.setModel(new DefaultComboBoxModel(new String[]{"1", "2", "3"}));

        jLabel1.setText("Priority");

        priorityCombo.setModel(new DefaultComboBoxModel(new String[]{"1", "2", "3"}));

        sentLabel.setText("Sent");

        dueDateLabel.setText("Due Date");

        jLabel2.setText("Archived");

        submitGeneralBtn.setText("Submit");
        submitGeneralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitGeneralBtnActionPerformed(evt);
            }
        });

        clearGeneral.setText("Clear");

        clearGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearGeneralActionPerformed(evt);
            }
        });

        createdByLabel.setText("Created By");



        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(createdByLabel)
                                        .addComponent(jLabel2)
                                        .addComponent(dueDateLabel)
                                        .addComponent(sentLabel)
                                        .addComponent(jLabel1)
                                        .addComponent(statusLabel)
                                        .addComponent(createdDateLabel)
                                        .addComponent(orderQuantityLabel)
                                        .addComponent(jobNameLabel))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(submitGeneralBtn)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(clearGeneral))
                                                .addComponent(jobNameTxt, GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                                .addComponent(orderQuantityTxt, GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                                .addComponent(statusCombo, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                                                .addComponent(priorityCombo, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                                                .addComponent(sentCheck)
                                                .addComponent(archaivedCheck))
                                        .addComponent(createdByCombo, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(createdDateTxt, GroupLayout.PREFERRED_SIZE, 245, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dueDateTxt, GroupLayout.PREFERRED_SIZE, 245, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jobNameTxt, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jobNameLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(orderQuantityLabel)
                                        .addComponent(orderQuantityTxt, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(createdDateLabel)
                                        .addComponent(createdDateTxt, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(createdByCombo, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(createdByLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(statusLabel)
                                        .addComponent(statusCombo, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(priorityCombo, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(sentLabel)
                                        .addComponent(sentCheck))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(dueDateLabel)
                                        .addComponent(dueDateTxt, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(archaivedCheck))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(submitGeneralBtn)
                                        .addComponent(clearGeneral))
                                .addContainerGap())
        );

        jTabbedPane1.addTab("General Information", jPanel1);

        paymentTermLabel.setText("Payment Term");



        jLabel5.setText("Delivery Term");



        jLabel6.setText("Due Date");

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(paymentTermLabel))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(deliveryTermCombo, GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE)
                            .addComponent(paymentTermCombo, GroupLayout.Alignment.LEADING, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(dueDateTermsCondition, GroupLayout.PREFERRED_SIZE, 245, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentTermLabel)
                    .addComponent(paymentTermCombo, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(deliveryTermCombo, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(dueDateTermsCondition, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Terms and Conditions", jPanel3);

        jLabel3.setText("Customer ");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        organizationLbl.setText("Organization");

        jLabel4.setText("Address");

        customerCombo.setModel(new DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        submitDetailBtn.setText("Submit");

        cancelDetailBtn.setText("Cancel");

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(organizationLbl)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(submitDetailBtn)
                        .addGap(18, 18, 18)
                        .addComponent(cancelDetailBtn))
                    .addComponent(organizationTxt, GroupLayout.PREFERRED_SIZE, 245, GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTxt, GroupLayout.PREFERRED_SIZE, 245, GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customerCombo, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationLbl)
                    .addComponent(organizationTxt, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addressTxt, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(submitDetailBtn)
                    .addComponent(cancelDetailBtn))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Detail", jPanel2);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents




    private void submitGeneralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitGeneralBtnActionPerformed
        JOptionPane.showConfirmDialog(this, "Submitted");
        JSONObject salesOrderObject = new JSONObject();
        try {
            Item createdBy = (Item)createdByCombo.getSelectedItem();
            salesOrderObject.put("jobName", jobNameTxt.getText());
            salesOrderObject.put("orderQuantity", orderQuantityTxt.getText());
            salesOrderObject.put("createdDate", createdDateTxt.getDate().toString());
            salesOrderObject.put("createdBy", createdBy.getId());
            salesOrderObject.put("status", statusCombo.getSelectedItem().toString());
            salesOrderObject.put("priority", priorityCombo.getSelectedItem().toString());
            salesOrderObject.put("isSent", sentCheck.isSelected());
            System.out.println("due date = " + dueDateTxt.getDate());
            salesOrderObject.put("dueDate", dueDateTxt.getDate().toString());
            salesOrderObject.put("isArchived", archaivedCheck.isSelected());
            
        } catch (JSONException ex) {
            Logger.getLogger(SalesOrderCreate.class.getName()).log(Level.SEVERE, null, ex);
        }

        String restEndPoint = Login.getRestEndPoint();
        String resource = "salesOrder";



        RESTFeed restFeed = new RESTFeed(InventoryConstants.MEDIA_JSON,
                InventoryConstants.MEDIA_JSON,InventoryConstants.POST,
                restEndPoint, resource);
        restFeed.setJsonObject(salesOrderObject);
        try {
            restFeed.restInitialization();
            JOptionPane.showMessageDialog (this, "General information saved successfully", "Sales Order", JOptionPane.INFORMATION_MESSAGE);
        } catch (MalformedURLException ex) {
            Logger.getLogger(SalesOrderCreate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SalesOrderCreate.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_submitGeneralBtnActionPerformed

    private void clearGeneralActionPerformed(java.awt.event.ActionEvent evt) {
        clearGeneral();
    }

    private void clearGeneral(){
        jobNameTxt.setText("");
        orderQuantityTxt.setText("");
//        dueDateTxt.setDate(null);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SalesOrderCreate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(SalesOrderCreate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(SalesOrderCreate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(SalesOrderCreate.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SalesOrderCreate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField addressTxt;
    private JCheckBox archaivedCheck;
    private JButton cancelDetailBtn;
    private JButton clearGeneral;
    private JComboBox createdByCombo;
    private JLabel createdByLabel;
    private JLabel createdDateLabel;
    private com.toedter.calendar.JDateChooser createdDateTxt;
    private JComboBox customerCombo;
    private JComboBox deliveryTermCombo;
    private JLabel dueDateLabel;
    private com.toedter.calendar.JDateChooser dueDateTermsCondition;
    private com.toedter.calendar.JDateChooser dueDateTxt;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JTabbedPane jTabbedPane1;
    private JLabel jobNameLabel;
    private JTextField jobNameTxt;
    private JLabel orderQuantityLabel;
    private JTextField orderQuantityTxt;
    private JLabel organizationLbl;
    private JTextField organizationTxt;
    private JComboBox paymentTermCombo;
    private JLabel paymentTermLabel;
    private JComboBox priorityCombo;
    private JCheckBox sentCheck;
    private JLabel sentLabel;
    private JComboBox statusCombo;
    private JLabel statusLabel;
    private JButton submitDetailBtn;
    private JButton submitGeneralBtn;
    private ItemCreationCombo itemCreationCombo;
    // End of variables declaration//GEN-END:variables
}
