/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WareHouseGrid.java
 *
 * Created on Aug 11, 2012, 9:12:05 PM
 */
package com.wings4.client;

import com.wings4.util.InventoryInternalBase;

import javax.swing.*;

/**
 *
 * @author ronnie
 */
public class WareHouseGrid extends InventoryInternalBase {

    private static volatile WareHouseGrid instance = null;
    private JScrollPane wareHouseGridPanel;

    /** Creates new form WareHouseGrid */
    private WareHouseGrid() {
        initComponents();
    }

    public static WareHouseGrid getInstance() {
        if (instance == null) {
            synchronized (WareHouseGrid.class){
                if (instance == null) {
                    instance = new WareHouseGrid();
                }
            }
        }

        return instance;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new WareHouseGrid().setVisible(true);
            }
        });
    }
}
