/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wings4;

/**
 *
 * @author Administrator
 */
public class InventoryDesktop extends javax.swing.JFrame {

    /**
     * Creates new form InventoryDesktop
     */
    public InventoryDesktop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jMenu2 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        inventoryMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loginMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        generalMenu = new javax.swing.JMenu();
        dashboardMenuItem = new javax.swing.JMenuItem();
        reportsMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        categoryMenuItem = new javax.swing.JMenuItem();
        productMenuItem = new javax.swing.JMenuItem();
        inventoryMenuItem = new javax.swing.JMenuItem();
        transferOrderMenuItem = new javax.swing.JMenuItem();
        salesMenu = new javax.swing.JMenu();
        salesOrderMenuItem = new javax.swing.JMenuItem();
        shippingItem = new javax.swing.JMenuItem();
        customerMenuItem = new javax.swing.JMenuItem();
        receivingMenuItem = new javax.swing.JMenu();
        purchageOrderMenuItem = new javax.swing.JMenuItem();
        vendorMenuItem = new javax.swing.JMenuItem();
        receivingMenu = new javax.swing.JMenuItem();
        manufaccturingMenu = new javax.swing.JMenu();
        billOfMaterialMenuItem = new javax.swing.JMenuItem();
        reportsMenu = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory");

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        fileMenu.setText("File");

        loginMenuItem.setText("Login");
        fileMenu.add(loginMenuItem);

        logoutMenuItem.setText("Logout");
        fileMenu.add(logoutMenuItem);

        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);
        fileMenu.add(jSeparator3);

        inventoryMenuBar.add(fileMenu);

        generalMenu.setText("General");

        dashboardMenuItem.setText("Dashboard");
        generalMenu.add(dashboardMenuItem);

        reportsMenuItem.setText("Reports");
        generalMenu.add(reportsMenuItem);

        inventoryMenuBar.add(generalMenu);

        jMenu3.setText("Materials");

        categoryMenuItem.setText("Category");
        jMenu3.add(categoryMenuItem);

        productMenuItem.setText("Product");
        jMenu3.add(productMenuItem);

        inventoryMenuItem.setText("Inventory");
        jMenu3.add(inventoryMenuItem);

        transferOrderMenuItem.setText("Transfer Order");
        jMenu3.add(transferOrderMenuItem);

        inventoryMenuBar.add(jMenu3);

        salesMenu.setText("Sales");

        salesOrderMenuItem.setText("Sales Order");
        salesMenu.add(salesOrderMenuItem);

        shippingItem.setText("Shipping");
        salesMenu.add(shippingItem);

        customerMenuItem.setText("Customer");
        salesMenu.add(customerMenuItem);

        inventoryMenuBar.add(salesMenu);

        receivingMenuItem.setText("Purchasing");

        purchageOrderMenuItem.setText("Purchage Order");
        receivingMenuItem.add(purchageOrderMenuItem);

        vendorMenuItem.setText("Vendor");
        receivingMenuItem.add(vendorMenuItem);

        receivingMenu.setText("Receiving");
        receivingMenuItem.add(receivingMenu);

        inventoryMenuBar.add(receivingMenuItem);

        manufaccturingMenu.setText("Manufacturing");

        billOfMaterialMenuItem.setText("Bill of Mateerial");
        manufaccturingMenu.add(billOfMaterialMenuItem);

        inventoryMenuBar.add(manufaccturingMenu);

        reportsMenu.setText("Reports");
        inventoryMenuBar.add(reportsMenu);

        setJMenuBar(inventoryMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InventoryDesktop().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem billOfMaterialMenuItem;
    private javax.swing.JMenuItem categoryMenuItem;
    private javax.swing.JMenuItem customerMenuItem;
    private javax.swing.JMenuItem dashboardMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu generalMenu;
    private javax.swing.JMenuBar inventoryMenuBar;
    private javax.swing.JMenuItem inventoryMenuItem;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenu manufaccturingMenu;
    private javax.swing.JMenuItem productMenuItem;
    private javax.swing.JMenuItem purchageOrderMenuItem;
    private javax.swing.JMenuItem receivingMenu;
    private javax.swing.JMenu receivingMenuItem;
    private javax.swing.JMenu reportsMenu;
    private javax.swing.JMenuItem reportsMenuItem;
    private javax.swing.JMenu salesMenu;
    private javax.swing.JMenuItem salesOrderMenuItem;
    private javax.swing.JMenuItem shippingItem;
    private javax.swing.JMenuItem transferOrderMenuItem;
    private javax.swing.JMenuItem vendorMenuItem;
    // End of variables declaration//GEN-END:variables
}
